language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install: pip install flake8 coverage
script:
  - python setup.py check
  - flake8 .
  - coverage run --branch --source pyccup -m unittest discover
  - coverage report --fail-under=100
